# Generated by Django 5.1.3 on 2024-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_student_email_alter_student_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
