# Generated by Django 5.1.3 on 2024-11-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_educationhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_name", models.CharField(max_length=100)),
                ("issued_by", models.CharField(max_length=100)),
                ("date_issued", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("certificate_file", models.FileField(upload_to="certificates/")),
                (
                    "sudent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
