# Generated by Django 5.1.3 on 2024-11-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(null=True, upload_to="certificates/"),
        ),
    ]
