# Generated by Django 5.1.3 on 2024-11-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_rename_sudent_certificate_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
