# Generated by Django 5.1.3 on 2024-11-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_alter_certificate_certificate_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="student",
            new_name="c_student",
        ),
    ]
